#!/bin/sh
#
# Startup script for AviAlert
#
case "$1" in
  start)
    printf "Starting AviAlert Services: "
    sleep 5
    date -s "2026-04-19 10:00:00"
    depmod -a
    modprobe snd
    modprobe snd-pcm
    modprobe snd-usb-audio
    modprobe birdclassifier
    sleep 2
    # Start WiFi
    wpa_supplicant -B -i wlan0 -c /etc/wpa_supplicant.conf
    sleep 3
    udhcpc -i wlan0
    sleep 2
    python3 /root/python-scripts/main.py > /var/log/avialert.log 2>&1 &
    echo "OK"
    ;;
  stop)
    printf "Stopping AviAlert: "
    start-stop-daemon -K -q -n python3
    echo "OK"
    ;;
  restart|reload)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
exit 0
