#!/bin/sh

case "$1" in
  start)
    echo "Starting Bird Classifier System..."
    
    # 1. Load the kernel module
    # Ensure the path matches where your _INSTALL_TARGET_CMDS put the file
    # insmod /lib/modules/$(uname -r)/extra/birdclassifier.ko
    
    # 2. Wait a moment for /dev/birdclassifier to be created by the kernel
    # sleep 1
    
    # 3. Start the Python script in the background
    # Use '&' so the boot process doesn't hang waiting for the script
    python3 /usr/AESD-project/main.py &
    ;;
  stop)
    # echo "Stopping Bird Classifier System..."
    # Kill the python script
    killall python3
    # Unload the module
    # rmmod birdclassifier
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit 0